# Generated by Django 3.0.4 on 2020-06-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('item_serial_number', models.CharField(max_length=200, unique=True)),
                ('faulty_description', models.TextField()),
                ('from_location', models.CharField(choices=[('None', 'None'), ('Land Admin', 'Land Admin'), ('Land Registration', 'Land Registration'), ('Third Floor', 'Third Floor'), ('Fourth Floor Wing B', 'Fourth Floor Wing B'), ('Seventh Floor', 'Seventh Floor'), ('Tenth Floor Wing C', 'Tenth Floor Wing C'), ('Tenth Floor Data Entry', 'Tenth Floor Data Entry'), ('Tenth Floor Former Prevalidation Room', 'Tenth Floor Former Prevalidation Room')], default='None', max_length=200)),
                ('repaired', models.BooleanField(default=False)),
                ('date_repaired', models.DateTimeField(auto_now_add=True, null=True)),
                ('location_returned', models.CharField(choices=[('None', 'None'), ('Land Admin', 'Land Admin'), ('Land Registration', 'Land Registration'), ('Third Floor', 'Third Floor'), ('Fourth Floor Wing B', 'Fourth Floor Wing B'), ('Seventh Floor', 'Seventh Floor'), ('Tenth Floor Wing C', 'Tenth Floor Wing C'), ('Tenth Floor Data Entry', 'Tenth Floor Data Entry'), ('Tenth Floor Former Prevalidation Room', 'Tenth Floor Former Prevalidation Room')], default='None', max_length=200)),
            ],
        ),
    ]
