# Generated by Django 3.0.4 on 2020-06-20 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faulty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faulty',
            name='date_repaired',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
