# Generated by Django 3.0.8 on 2020-10-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faulty', '0002_auto_20200621_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faulty',
            name='from_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faulty',
            name='location_returned',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
