# Generated by Django 3.0.4 on 2020-04-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_admin', '0002_auto_20200423_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landadminbarcodescanner',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='landadmindesktop',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
