# Generated by Django 3.0.4 on 2020-04-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_admin', '0003_auto_20200423_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landadminbarcodescanner',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
