# Generated by Django 3.0.4 on 2020-06-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_admin', '0005_auto_20200609_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landadminbarcodescanner',
            old_name='created_by',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='landadmindesktop',
            old_name='created_by',
            new_name='updated_by',
        ),
    ]
