# Generated by Django 3.0.8 on 2020-10-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_admin', '0007_auto_20200817_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landadmindesktop',
            name='cpu_serial_number',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='landadmindesktop',
            name='keyboard_serial_number',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='landadmindesktop',
            name='monitor_serial_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
