# Generated by Django 3.0.8 on 2020-07-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='business_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockin',
            name='item_ref_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
