# Generated by Django 3.0.8 on 2020-10-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0002_auto_20200727_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='item_ref_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
