# Generated by Django 3.0.4 on 2020-06-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankinghall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankinghallbarcodescanner',
            old_name='created_by',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='bankinghalldesktop',
            old_name='created_by',
            new_name='updated_by',
        ),
    ]
