# Generated by Django 3.0.4 on 2020-06-30 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EighthFloorDeskTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_serial_number', models.CharField(max_length=200)),
                ('monitor_serial_number', models.CharField(max_length=200)),
                ('keyboard_serial_number', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(choices=[('In Current Location', 'In Current Location'), ('Land Registration', 'Land Registration'), ('Third Floor', 'Third Floor'), ('Fourth Floor Wing B', 'Fourth Floor Wing B'), ('Seventh Floor', 'Seventh Floor'), ('Tenth Floor Wing C', 'Tenth Floor Wing C'), ('Tenth Floor Data Entry', 'Tenth Floor Data Entry'), ('Tenth Floor Former Prevalidation Room', 'Tenth Floor Former Prevalidation Room'), ('Ground Floor', 'Ground Floor')], default='In Current Location', max_length=200)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
