# Generated by Django 3.0.8 on 2020-08-05 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seventhfloor', '0002_auto_20200609_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='seventhfloordesktop',
            name='location',
        ),
        migrations.AddField(
            model_name='seventhfloordesktop',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seventhfloor.Floor'),
        ),
    ]
