# Generated by Django 3.0.8 on 2020-08-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seventhfloor', '0003_auto_20200805_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seventhfloordesktop',
            name='floor',
        ),
        migrations.AddField(
            model_name='seventhfloordesktop',
            name='location',
            field=models.CharField(choices=[('In Current Location', 'In Current Location'), ('Land Registration', 'Land Registration'), ('Third Floor', 'Third Floor'), ('Fourth Floor Wing A', 'Fourth Floor Wing A'), ('Fourth Floor Wing B', 'Fourth Floor Wing B'), ('Land Admin', 'Land Admin'), ('Tenth Floor Wing C', 'Tenth Floor Wing C'), ('Tenth Floor Data Entry', 'Tenth Floor Data Entry'), ('Tenth Floor Former Prevalidation Room', 'Tenth Floor Former Prevalidation Room')], default='In Current Location', max_length=200),
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
