# Generated by Django 3.0.8 on 2020-09-09 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('count', models.CharField(blank=True, max_length=255, null=True)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason_for_order', models.TextField()),
                ('ordered', models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted')], default='pending', max_length=255)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
